# Fabric Properties
  minecraft_version = 26.1

# Fabric Mod Metadata
  minecraft_dependency =26.1
  carpet_dependency = >=26.1-beta-6

# Mod Dependency
  carpet_core_version = 26.1-beta-6+v260212
  g4mespeed_version = 1.4.13-mc1.21.11
  lithium_version = com.github.Fallen-Breath:lithium-fabric:34966dcdad
  malilib_version = maven.modrinth:malilib:0.28.0
  mod_menu_version = 18.0.0-alpha.7
fabric_api_version = 0.143.14+26.1
